spring.application.name=medz-loader
spring.datasource.url=jdbc:postgresql://localhost:5432/medz
spring.datasource.username=postgres
spring.datasource.password=password
spring.batch.jdbc.initialize-schema=always
